Sorbet:
  Enabled: true

Sorbet/ValidSigil:
  Enabled: true
  Exclude:
    - lib/cli/kit/sorbet_runtime_stub.rb

Sorbet/FalseSigil:
  Enabled: false

Sorbet/TrueSigil:
  Enabled: true
  Include:
    - "**/*.rb"
    - "**/*.rbi"
    - "**/*.rake"
    - "**/*.ru"
  Exclude:
    - lib/cli/kit/sorbet_runtime_stub.rb
    - "test/**/*"
    - "lib/cli/kit/support/test_helper.rb"

Sorbet/EnforceSigilOrder:
  Enabled: true

Sorbet/EnforceSignatures:
  Enabled: true
  Style: rbs
  Exclude:
    - lib/cli/kit/sorbet_runtime_stub.rb
    - "test/**/*"
    - bin/testunit
    - "lib/cli/kit/support/test_helper.rb"

Sorbet/SignatureBuildOrder:
  Enabled: true

Sorbet/KeywordArgumentOrdering:
  Enabled: true

Sorbet/ConstantsFromStrings:
  Enabled: true
  Exclude:
    - "examples/**/*"

Sorbet/ForbidIncludeConstLiteral:
  Enabled: false
