# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi todo

# typed: strong
module CLI::UI::VERSION; end
module Example::Command; end
module Example::EntryPoint; end
module Example::ErrorHandler; end
module Example::Executor; end
module Example::Resolver; end
module Gen::Command; end
module Gen::Command; end
module Gen::Executor; end
module Gen::Resolver; end
